export const commentsItem: string;
export const itemComment: string;
export const commentTitle: string;
export const commentUsername: string;
export const commentFloor: string;
export const commentContent: string;
export const commentOperation: string;
export const commentLikeBtn: string;
export const subCommentBtn: string;
